version: '2.2'

services:
  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - cluster.name=docker-cluster
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$ELASTICSEACHT_CERTS_DIR/es01/es01.key
      - xpack.security.http.ssl.certificate_authorities=$ELASTICSEACHT_CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$ELASTICSEACHT_CERTS_DIR/es01/es01.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.certificate_authorities=$ELASTICSEACHT_CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$ELASTICSEACHT_CERTS_DIR/es01/es01.crt
      - xpack.security.transport.ssl.key=$ELASTICSEACHT_CERTS_DIR/es01/es01.key
      - "http_proxy=${http_proxy}"
      - "https_proxy=${http_proxy}"
      - "no_proxy=es01, es02, localhost, 127.*, 192.*"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes: ['esdata1:/usr/share/elasticsearch/data', './certs:$ELASTICSEACHT_CERTS_DIR']
    ports:
      - 9200:9200
  es02:
    container_name: es02
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - cluster.name=docker-cluster
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$ELASTICSEACHT_CERTS_DIR/es02/es02.key
      - xpack.security.http.ssl.certificate_authorities=$ELASTICSEACHT_CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$ELASTICSEACHT_CERTS_DIR/es02/es02.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.certificate_authorities=$ELASTICSEACHT_CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$ELASTICSEACHT_CERTS_DIR/es02/es02.crt
      - xpack.security.transport.ssl.key=$ELASTICSEACHT_CERTS_DIR/es02/es02.key
      - "http_proxy=${http_proxy}"
      - "https_proxy=${http_proxy}"
      - "no_proxy=es01, es02, localhost, 127.*, 192.*"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes: ['esdata2:/usr/share/elasticsearch/data', './certs:$ELASTICSEACHT_CERTS_DIR']

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana
    environment:
      HTTP_PROXY: "${http_proxy}"
      HTTPS_PROXY: "${http_proxy}"
      NO_PROXY: "es01, es02, localhost, 127.*, 192.*"
      KIBANA_PASSWORD: "${KIBANA_PASSWORD}"
    ports:
      - 8080:5601
    volumes: ['.:/usr/share/kibana/config']

volumes: {"esdata1": {"driver": "local"}, "esdata2": {"driver": "local"}}
